Repository agamm/comeback, pull requests merged in 2019-03, with the labels that each got.

#21 Add ability to run specific plugin
  Pipfile.lock
  comeback/main.py
  setup.py
Labels: enhancement

#23 Complete pycharm plugin to be cross platform
  README.md
  comeback/plugins/pycharm/main.py
  comeback/utils.py
Labels: enhancement

#24 Add mypy to the project
  CONTRIBUTING.md
  comeback/main.py
  comeback/plugins/__init__.py
  comeback/plugins/chrome/main.py
  comeback/plugins/pycharm/main.py
  comeback/plugins/vscode/main.py
  comeback/utils.py
Labels: enhancement

#35 Fix windows pycharm add global paths fixes
  comeback/main.py
  comeback/plugins/pycharm/main.py
Labels: bug

#36 Add global user selectable list
  comeback/main.py
  comeback/plugins/pycharm/main.py
Labels: enhancement, lit af
